<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gestión de archivos - Estadías</title><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet"><link href="${ctx}/assets/css/workflow.css" rel="stylesheet"></head><body>
<jsp:include page="/Layout/sidebar.jsp"/><main class="workflow-main"><h1 class="workflow-title">Gestión de archivos</h1><div class="workflow-subtitle">Solicitud de visita, Carta responsiva y Reporte</div>
<c:if test="${not empty error}"><div class="workflow-card" style="color:#991b1b"><c:out value="${error}"/></div></c:if>
<form class="workflow-card workflow-filters" action="${ctx}/estadias/documentos" method="get">
<div><label class="workflow-label">Buscar</label><input class="workflow-input" name="q" value="<c:out value='${param.q}'/>" placeholder="ID, docente, empresa, carrera"></div>
<div><label class="workflow-label">Tipo de documento</label><select class="workflow-select" name="tipo"><option value="">Los tres tipos</option><option value="SOLICITUD_VISITA">Solicitud de visita</option><option value="CARTA_RESPONSIVA">Carta responsiva</option><option value="REPORTE">Reporte</option></select></div><div></div><div></div><button class="workflow-btn navy"><i class="bi bi-search"></i> Buscar</button>
</form>
<div class="workflow-card" style="padding:0;overflow:auto"><table class="workflow-table"><thead><tr><th>Solicitud</th><th>Tipo</th><th>Docente</th><th>División</th><th>Carrera</th><th>Empresa</th><th>Estado</th><th>Revisar</th></tr></thead><tbody>
<c:forEach var="doc" items="${documentos}"><tr><td><c:out value="${doc.idVisitaFk}"/></td><td><c:out value="${doc.tipoLegible}"/></td><td><c:out value="${doc.docente}"/></td><td><c:out value="${doc.division}"/></td><td><c:out value="${doc.carrera}"/></td><td><c:out value="${doc.empresa}"/></td><td><span class="status"><c:out value="${doc.estadoLegible}"/></span></td><td><a class="workflow-btn navy" style="min-height:32px;padding:5px 14px" href="${ctx}${doc.tipoDocumento == 'REPORTE' ? '/estadias/reporte' : '/estadias/documento'}?idDocumento=${doc.idDocumento}"><i class="bi bi-eye"></i></a></td></tr></c:forEach>
<c:if test="${empty documentos}"><tr><td class="empty-row" colspan="8">Todavía no se han recibido documentos.</td></tr></c:if>
</tbody></table></div></main></body></html>
