<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Histórico de visitas</title><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="${ctx}/assets/css/workflow.css" rel="stylesheet"><style>.timeline{display:flex;align-items:center;gap:4px;min-width:250px}.node{width:19px;height:19px;border-radius:50%;background:#cbd5e1;display:grid;place-items:center;color:#fff;font-size:.65rem}.line{height:3px;flex:1;background:#cbd5e1}.node.done,.line.done{background:#f08a24}.node.final{box-shadow:0 0 0 4px #f08a2433}</style></head><body>
<jsp:include page="/Layout/sidebar.jsp"/><main class="workflow-main"><h1 class="workflow-title">Histórico de visitas</h1><div class="workflow-subtitle">Consulta los documentos y el cierre del reporte final</div>
    <form class="workflow-card workflow-filters" method="post" action="${ctx}/estadias/historico"><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><div><label class="workflow-label">Buscar</label><input class="workflow-input" name="q" value="<c:out value='${param.q}'/>" placeholder="Empresa, docente, división o carrera"></div><button class="workflow-btn navy"><i class="bi bi-search"></i> Buscar</button></form>
    <div class="workflow-card" style="padding:0;overflow:auto"><table class="workflow-table"><thead><tr><th>Empresa</th><th>Docente</th><th>División</th><th>Carrera</th><th>Fecha</th><th>Seguimiento</th><th>Documentos</th></tr></thead><tbody>
    <c:forEach var="sol" items="${solicitudes}"><tr><td><c:out value="${sol.empresa}"/></td><td><c:out value="${sol.docente}"/></td><td><c:out value="${sol.division}"/></td><td><c:out value="${sol.carrera}"/></td><td><c:out value="${sol.fechaInicio}"/></td><td><div class="timeline" title="Solicitud, carta, oficio y reporte"><span class="node done"><i class="bi bi-check"></i></span><span class="line done"></span><span class="node done"><i class="bi bi-check"></i></span><span class="line done"></span><span class="node done"><i class="bi bi-check"></i></span><span class="line ${sol.estado == 'COMPLETADA' ? 'done' : ''}"></span><span class="node ${sol.estado == 'COMPLETADA' ? 'done final' : ''}"><i class="bi bi-check"></i></span></div></td><td><button type="button" class="workflow-btn light" data-post-url="${ctx}/estadias/expediente" data-post-ref="<c:out value='${sol.referenceToken}'/>"><i class="bi bi-folder2-open"></i> Ver</button></td></tr></c:forEach>
    <c:if test="${empty solicitudes}"><tr><td class="empty-row" colspan="7">Aún no se han recibido visitas.</td></tr></c:if></tbody></table></div></main></body></html>
